apiVersion: v1
data:
  AWS_PASSWORD: Vk5xR1NuNmhYY05zYmRGMkw4bFVYODExNmVLWFN6S1A3MmhubmZqSA==
  AWS_USERNAME: QUtJQVRRREtXWEYySzJBRjVMTVc=
kind: Secret
metadata:
  creationTimestamp: "2020-07-25T19:40:24Z"
  name: secret
  namespace: default
  resourceVersion: "92835"
  selfLink: /api/v1/namespaces/default/secrets/secret
  uid: 2acdccd1-f6ba-4889-a4c6-a41db3b6b803
type: Opaque